version: 0.0.0.1
external-values:
  - username
  - password
  - download-folder
  - version
  - distr-type
  - name
default-values:
  test-mode: false
  timeout: 0
  try-count: 1
  time-limit: 3600
  use-eu-site: False
  save-accurately: False
